field_order = [
"""Jednostka"""
, """Czy program zawiera stronę tytułową? \n(Zaznaczamy tak, gdy ze strony tytułowej jasno wynika, dla której jednostki jest on stworzony i na jaki rok harcerski.)"""
, """Istnienie charakterystyki"""
, """Historia (Miejsce, data oraz okoliczności powołania, wymienienie drużynowych, którzy na przestrzeni dziejów przewodzili jednostce.)"""
, """Środowisko działania (Szczep, szkoła, osiedle, dzielnica itp.)"""
, """Stan liczebny (w jednostce koedukacyjnej powinien być podany z podziałem na dziewczynki i chłopców)"""
, """Opis kadry jednostki (Informacja pogłębiona zawiera imię i nazwisko każdego członka, jego wiek, stopień harcerski i instruktorski, pełnione funkcje, wykonywany zawód/zdobywane wykształcenie, staż ..."""
, """Informacja o funkcjonowaniu rady jednostki (informacja pogłębiona zawiera informację o członkach i spotkaniach)"""
, """Obrzędowość (informacja pogłębiona zawiera nazwy elementów wraz z wyjaśnieniem)"""
, """Instrumenty metodyczne - Obietnica Zucha/Przyrzeczenie Harcerskie (informacja pogłębiona zawiera zestawienie)"""
, """Instrumenty metodyczne - Gwiazdki zuchowe/Stopnie harcerskie  (informacja pogłębiona zawiera zestawienie)"""
, """Instrumenty metodyczne - wyzwania, sprawności, odznaki; (informacja pogłębiona zawiera zestawienie)"""
, """Instrumenty metodyczne - tropy lub sprawności zespołowe/zadania zespołowe/projekty starszoharcerskie/znaki służb, jeśli jednostka nie działała jeszcze nowym SIMem w poprzednim roku (+w informacji ..."""
, """Informacja o zbiórkach drużyny i zastępów"""
, """Informacja o szóstkach/zastępach"""
, """Dodatkowe informacje\n(Możliwość przyznania dodatkowych punktów za inne informacje zawarte w charakterystyce, np. miano gromady specjalnościowej,  HAL, HAZ, sprzęt lub elementy wymagające wyróżnien..."""
, """Uwagi\n(Miejsce na komentarz dotyczący charakterystyki.)"""
, """Istnienie analizy"""
, """Ilość plusów"""
, """Poprawność plusów (1 - niepoprawne, 4 - poprawne)"""
, """Ilość minusów"""
, """Poprawność minusów (1 - niepoprawne, 4 - poprawne)"""
, """Analiza wynika z charakterystyki"""
, """Uwagi\n(Miejsce na komentarz dotyczący analizy.)"""
, """Istnienie celów"""
, """Ilość"""
, """Poprawność celów (1 - niepoprawne, 4 - poprawne)"""
, """Cele wynikają z analizy"""
, """Uwagi\n(Miejsce na komentarz dotyczący celów.)"""
, """Analiza i cele korespondują z celami ze Statutu i postawami z Podstaw Wychowawczych ZHP\n\n(Przejrzyj jeszcze raz analizę i cele w programie, który sprawdzasz. Zaznacz poniżej te cele, do których od..."""
, """Istnienie zamierzeń"""
, """Ilość2"""
, """Poprawność zamierzeń (1 - niepoprawne, 4 - poprawne)"""
, """Zamierzenia wynikają z celów"""
, """Uwagi\nMiejsce na komentarz dotyczący zamierzeń."""
, """Istnienie zadań"""
, """Ilość3"""
, """Poprawność zadań (1 - niepoprawne, 4 - poprawne)"""
, """Zadania wynikają z zamierzeń"""
, """Uwagi\nMiejsce na komentarz dotyczący zadań."""
, """Istnienie harmonogramu"""
, """Termin"""
, """Temat"""
, """Krótki opis"""
, """Forma"""
, """Osoba odpowiedzialna"""
, """Harmonogram wynika z celów i zamierzeń"""
, """Uwagi\n(Miejsce na komentarz dotyczący harmonogramu.)"""
, """Ciekawość inicjatyw (1 - przeciętny, 4 - bardzo ciekawy)\n(Formy pracy, pomysły na działania, innowacje, wykorzystanie nietypowych metod i narzędzi)"""
, """Podejmowane działania\n(Do wewnątrz - jednostka, zastępy/szóstki. Na zewnątrz - np. sojusznicy, szkoła, sąsiedzi.)"""
, """Propozycje programowe\n(Mogą to być również propozycje z poprzednich lat.)"""
, """Estetyka"""
, """Dodatkowe punkty\n(Możliwość przyznania dodatkowych punktów za szczególne walory całego programu. W uwagach napisać, za co przyznano punkty.)"""
, """Uwagi\n(Miejsce na komentarz dotyczący całego programu.)"""
]